import express from 'express';
import { addCustomUser, changepass, deactivateaccount, deleteCustomUser, deleteroom, getCustomUser, quickify, quicklogin, quickroom, quickshowroom, quicksign, searchUser, showallroom, updateprofile, updateroom } from '../controller/main.controller.js';
import { checklogin } from '../middleware/checklogin.js';
import { upload } from '../middleware/upload.js';
import { veryfiTokan } from '../middleware/tokan.js';
export const router = express.Router();

router.get('/quickify',quickify);
router.post('/quicksign',upload.single('profilepic'),quicksign);
router.post('/quicklogin',checklogin,quicklogin);
router.post('/quickroom',upload.single('roompic'),quickroom);
router.get('/quickshowroom',quickshowroom);
router.delete('/delete-room',deleteroom);
router.get('/qshowAroom',veryfiTokan,showallroom);
router.put('/updateroom',updateroom);
router.put('/change-password',changepass);
router.put('/update-profile',upload.single('profilepic'),updateprofile);
router.post('/add-custom-user',addCustomUser);
router.post('/get-custom-user',getCustomUser);
router.delete('/delete-custom-room',deleteCustomUser);
router.get('/search-user',searchUser);
router.delete('/de-activate-account',deactivateaccount);